### ISSUE TITLE
Server crashed 

### ISSUE THREAD

**Issue by hbredin** [camomile-project/camomile-server#69]
```
http.js:1232
  var statusLine = 'HTTP/1.1 ' + statusCode.toString() + ' ' +
                                            ^
TypeError: Cannot call method 'toString' of undefined
    at ServerResponse.writeHead (http.js:1232:45)
    at ServerResponse.writeHead (/app/node_modules/morgan/node_modules/on-headers/index.js:55:19)
    at ServerResponse.writeHead (/app/node_modules/express-session/node_modules/on-headers/index.js:55:19)
    at ServerResponse._implicitHeader (http.js:1183:8)
    at ServerResponse.OutgoingMessage.write (http.js:886:10)
    at write (_stream_readable.js:602:24)
    at flow (_stream_readable.js:611:7)
    at ReadStream.pipeOnReadable (_stream_readable.js:643:5)
    at ReadStream.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at emitReadable (_stream_readable.js:423:5)
    at readableAddChunk (_stream_readable.js:166:9)
    at ReadStream.Readable.push (_stream_readable.js:128:10)
    at onread (fs.js:1575:12)
    at Object.wrapper [as oncomplete] (fs.js:466:17)
```

**Comment by hbredin** [comment]
75415aa907d6c11bec970024f8e8432340acd1d0 probably fixed this.
