### ISSUE TITLE
No parser check if the request has a good formatting  

### ISSUE THREAD

**Issue by johannpoignant** [camomile-project/camomile-server#7]
In this request is missing " after role

$ curl -i -X PUT http://localhost:3000/user/54228bf9c01c5fac19e227b6 --data '{"username":"name3", "affiliation": "org2", "role : "user"}' -H "Content-Type: application/json" --cookie "cookies.txt"
HTTP/1.1 400 Bad Request
X-Powered-By: Express
Content-Type: text/plain
Date: Wed, 24 Sep 2014 14:24:09 GMT
Connection: keep-alive
Transfer-Encoding: chunked

SyntaxError: Unexpected token u
    at Object.parse (native)
    at IncomingMessage.<anonymous> (/Users/poignant/Documents/Dev/camomile-server/node_modules/express/node_modules/connect/lib/middleware/json.js:76:27)
    at IncomingMessage.emit (events.js:92:17)
    at _stream_readable.js:943:16
    at process._tickCallback (node.js:419:13)

**Comment by hbredin** [comment]
[ValidateJS](http://validatejs.org) could be a good library to do this.
